### ISSUE TITLE
Document how to install Bespoke.js themes

### ISSUE THREAD

**Issue by mraible** [opendevise/presentation-bespoke-starter#1]
On the bespoke project site, it references a few [official themes](https://github.com/bespokejs/bespoke#official-themes). 

I tried installing one and referencing it in `main.js`, but it didn't work as expected.

How can I create a presentation from this project and use the same theme as [this presentation](http://markdalgleish.github.io/presentation-build-wars-gulp-vs-grunt/)?

**Comment by mojavelinux** [comment]
Since CSS is highly dependent on HTML structure, it's very likely we're going to need to develop our own themes for Bespoke.js that go with the Asciidoctor Bespoke.js converter.

The first theme I planned to create was the one for Shower demo (called Ribbon, to be packaged as bespoke-theme-ribbon) since it's very clean and likely to appeal to a lot of people that like deck.js.

Until that time, I recommend crafting your own CSS. In fact, even with themes, we're going to continue encouraging users to dive into the CSS because each presentation should have its own style. The themes will be targeted for groups (like a training group) or when time is of the essence.

**Comment by mraible** [comment]
Hmmm, I was hoping to use Asciidoctor's Bespoke.js support to whip up a presentation quick-and-easy. Is there another presentation framework that Asciidoctor supports that's easy to create a presentation with?

**Comment by mojavelinux** [comment]
Why don't you just build on the Shower demo? It's basically the same as the starter presentation with the addition of the theme.

Another option is the [Reveal.js converter](https://github.com/asciidoctor/asciidoctor-reveal.js).

The lack of available options is exactly why we're working on Asciidoctor Bespoke.js. A better toolchain is needed, and both deck.js and Reveal.js are standing still.

**Comment by mojavelinux** [comment]
As you can tell, I'm quite passionate about lighting a fire under this situation ;)

**Comment by mraible** [comment]
@mojavelinux Thanks for the idea to clone the [shower presentation](https://github.com/opendevise/bespoke-emulating-shower)!

**Comment by mraible** [comment]
I gotta say, I do like the default image for the title slide. ;)

![screen shot 2016-04-12 at 11 19 34 pm](https://cloud.githubusercontent.com/assets/17892/14483537/1eb72292-0105-11e6-83fd-8ce7416a09c9.png)
